version: 2.1

# First define some constants
working_dir_name: &workingDirName ~/workspace
java_docker_image: &javaMavenDockerImage circleci/openjdk:11.0.3-stretch
git_docker_image: &gitDockerImage alpine/git

# Define some configuration
working_dir: &workingDirectory
    working_directory: *workingDirName
java_runtime: &javaRuntime
    docker:
        - image: *javaMavenDockerImage

commands:
    retrieve_workspace:
        description: "Retrieves the working directory in the workspace"
        steps:
            - attach_workspace:
                at: *workingDirName

    save_workspace:
        description: "Saves the working directory as the workspace"
        steps:
            - persist_to_workspace:
                root: *workingDirName
                paths:
                    - .

    retrieve_maven_local_repository_from_cache:
        description: "Retrieves the Maven's Local Repository from Cache, based on poms' checksum"
        steps:
            - run:
                name: Aggregating all project's pom files in a single file
                command: |
                    rm -f .all-poms
                    find . -type f -regex ".*/pom.xml" | sort -n | xargs cat >> .all-poms ;
            - restore_cache:
                # First try with the pom's aggregation checksum. If not available, get most recent
                keys:
                    - cache-{{ .Environment.SERVICE_NAME }}-{{ .Environment.CACHE_VERSION }}-{{ checksum ".all-poms" }}
                    - cache-{{ .Environment.SERVICE_NAME }}-{{ .Environment.CACHE_VERSION }}-

    generate_new_maven_local_repository:
        description: "Generates a new Maven local repository (when checksum is different only)"
        steps:
            - retrieve_maven_local_repository_from_cache
            - run:
                name: Downloading required dependencies and plugins
                command: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies -P continuous-integration -P docker-build
            - save_cache:
                key: cache-{{ .Environment.SERVICE_NAME }}-{{ .Environment.CACHE_VERSION }}-{{ checksum ".all-poms" }}
                paths:
                    - ~/.m2

    compile_code:
        description: "Compiles sources of the Maven's project"
        steps:
            - run:
                name: Compiling source code
                command: mvn clean compile -P continuous-integration -B -V

    test_code:
        description: "Performs tests using the Maven's test phase"
        steps:
            - run:
                name: Running tests
                command: mvn test -P continuous-integration -B -DforkCount=0 --fail-at-end

    save_test_results:
        description: "Aggregates the test results and stores them."
        steps:
            - run:
                name: Aggregating all project's tests results
                command: |
                    mkdir -p ~/test-results/junit/
                    find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
                when: always
            - store_test_results:
                    path: ~/test-results
            - store_artifacts:
                    path: ~/test-results/junit

    create_docker_image:
        description: "Creates a Docker Image using Maven"
        steps:
            - run:
                name: Creating Docker Image
                command: mvn package -DskipTests=true -P continuous-integration -P docker-build -B -Dtag=putodemierda


jobs:
    compile_and_test:
        # Apply working directory and docker image
        <<: *workingDirectory
        <<: *javaRuntime

        steps:
            - checkout
            - generate_new_maven_local_repository
            - compile_code
            - test_code
            - save_test_results
            - save_workspace

    build_and_push_docker_image:
        # Apply working directory and docker image
        <<: *workingDirectory
        <<: *javaRuntime

        steps:
            - retrieve_workspace
            - retrieve_maven_local_repository_from_cache
            - setup_remote_docker
            - create_docker_image


workflows:
    version: 2.1
    ci_cd:
        jobs:
            - compile_and_test
            - build_and_push_docker_image:
                  requires:
                      - compile_and_test
