version: 2.1

# First define some constants
working_dir_name: &workingDirName ~/workspace
git_docker_image: &gitDockerImage alpine/git
java_docker_image: &javaMavenDockerImage circleci/openjdk:11.0.2-jdk

# Define some configuration
working_dir: &workingDirectory
    working_directory: *workingDirName
java_runtime: &javaRuntime
    docker:
        - image: *javaMavenDockerImage

# Some cache steps...
save_maven_local_repository_in_cache: &saveMavenLocalRepositoryInCache
    save_cache:
        key: maven-cache-{{ .Environment.SERVICE_NAME }}-{{ .Environment.CACHE_VERSION }}
        paths:
            - ~/.m2
retrieve_maven_local_repository_from_cache: &restoreMavenLocalRepositoryInCache
    restore_cache:
        key: maven-cache-{{ .Environment.SERVICE_NAME }}-{{ .Environment.CACHE_VERSION }}





concatenate_poms: &concatenatePoms
    run:
        name: Calculate digest
        command: |
            rm -f all-poms
            find . -type f -regex ".*/pom.xml" | sort -n | xargs cat >> all-poms ;



save_maven_local_repository_in_cache2: &saveMavenLocalRepositoryInCache2
    save_cache:
        key: maven-cache-{{ .Environment.SERVICE_NAME }}-{{ checksum "all-poms" }}
        paths:
            - ~/.m2

retrieve_maven_local_repository_from_cache2: &restoreMavenLocalRepositoryInCache2
    restore_cache:
        keys:
            - maven-cache-{{ .Environment.SERVICE_NAME }}-{{ checksum "all-poms" }} # First try actual version
            - maven-cache-{{ .Environment.SERVICE_NAME }}-                          # Then, most recent cache


jobs:
    checkout_code:
        # For the checkout job only apply the working directory
        <<: *workingDirectory

        # Use the Alpine's Docker image to checkout code
        docker:
            - image: *gitDockerImage

        steps:
            # Download code from VCS
            - checkout

            # Persist the downloaded code into the workspace
            - persist_to_workspace:
                root: *workingDirName
                paths:
                    - ./

#    prepare_maven_local_repository:


    compile:
        # Apply working directory and docker image
        <<: *workingDirectory
        <<: *javaRuntime

        steps:
            # Restore workspace
            - attach_workspace:
                  at: *workingDirName

            # Restore actual cache (Maven's Local Repository)
#            - <<: *restoreMavenLocalRepositoryInCache

            - <<: *concatenatePoms
            - <<: *restoreMavenLocalRepositoryInCache2

            # Download all dependencies and plugins
            - run:
                name: Download required dependencies and plugins
                command: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies

            # Store in cache the Maven's Local Repository
#            - <<: *saveMavenLocalRepositoryInCache
            - <<: *saveMavenLocalRepositoryInCache2

            # Compile modules. This will download missing dependencies (not in cache)
            - run:
                name: Compile source code
                command: mvn clean compile -DskipTests=true -P continuous-integration -B -V

            # Persist the built stuff (compiled coded, artifacts, etc.)
            - persist_to_workspace:
                root: *workingDirName
                paths:
                    - ./

    test:
        # Apply working directory and docker image
        <<: *workingDirectory
        <<: *javaRuntime

        steps:
            # Restore workspace
            - attach_workspace:
                at: *workingDirName

#            - <<: *restoreMavenLocalRepositoryInCache
            - <<: *concatenatePoms
            - <<: *restoreMavenLocalRepositoryInCache2

            # Run tests! (Artifacts are already installed in the build job)
            - run:
                name: Run tests
                command: mvn test -P continuous-integration -B --fail-at-end

            # Move all tests results into a single directory
            - run:
                name: Save tests results
                command: |
                    mkdir -p ~/test-results/junit/
                    find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
                when: always

            # Store test results
            - store_test_results:
                path: ~/test-results

            - store_artifacts:
                path: ~/test-results/junit


workflows:
    version: 2.1
    compile_and_test:
        jobs:
            - checkout_code
            - compile:
                requires:
                    - checkout_code
            - test:
                requires:
                    - compile
